
gravelpit:
  image: danieldent/rancher-metadata-dump
  tty: true
  stdin_open: true
  entrypoint:
    - /bin/bash
  labels:
    io.rancher.sidekicks: dumptruck
    io.rancher.container.pull_image: always
  volumes_from:
    - dumptruck

dumptruck:
  image: danieldent/rancher-metadata-dump
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
  command:
    - YAML
    - /rancher-metadata-dumper/test-dumptruck-output.yml

